"""add finding validation_reasoning

Revision ID: 3155935e555c
Revises: de91ac9857d7
Create Date: 2026-06-30 16:09:13.328686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3155935e555c'
down_revision: Union[str, Sequence[str], None] = 'de91ac9857d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('validation_reasoning', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'validation_reasoning')
    # ### end Alembic commands ###
