"""add created_at to scan_jobs

Revision ID: de91ac9857d7
Revises: 254ed6990d72
Create Date: 2026-06-29 23:50:28.393825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de91ac9857d7'
down_revision: Union[str, Sequence[str], None] = '254ed6990d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_jobs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_jobs', 'created_at')
    # ### end Alembic commands ###
