apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sentinelai.fullname" . }}-postgres-data
  labels:
    {{- include "sentinelai.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgres.storageClassName }}
  storageClassName: {{ .Values.postgres.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
